export default {
  // auth api calls
  LOGIN_USER: 'LOGIN_USER',
  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_TWITTER: 'REGISTER_USER_TWITTER',
  LOGIN_USER_TWITTER: 'LOGIN_USER_TWITTER',
  REGISTER_USER_FACEBOOK: 'REGISTER_USER_FACEBOOK',
  LOGIN_USER_FACEBOOK: 'LOGIN_USER_FACEBOOK',
  REGISTER_USER_GOOGLE: 'REGISTER_USER_GOOGLE',
  SOCIAL_REGISTER: 'SOCIAL_REGISTER',
  LOGIN_USER_GOOGLE: 'LOGIN_USER_GOOGLE',
  UPDATE_USER: 'UPDATE_USER',
  SEND_RESET_LINK: 'SEND_RESET_LINK',
  RESET_PASSWORD: 'RESET_PASSWORD',
  LOGOUT_FROM_ALL_DEVICES: 'LOGOUT_FROM_ALL_DEVICES',
  CHANGE_PIN: 'CHANGE_PIN',
  GET_PREVIOUS_SCREEN: "GET_PREVIOUS_SCREEN",

  // user api calls
  GET_USER_PERSONAL_INFO: 'GET_USER_PERSONAL_INFO',
  GET_USER_TAXPAYER_INFO: 'GET_USER_TAXPAYER_INFO',
  UPDATE_USER_PERSONAL_INFO: 'UPDATE_USER_PERSONAL_INFO',
  UPDATE_USER_ADDRESS_INFO: 'UPDATE_USER_ADDRESS_INFO',
  UPDATE_USER_TAXPAYER_INFO: 'UPDATE_USER_TAXPAYER_INFO',
  UPLOAD_PLOFILE_IMAGE: 'UPLOAD_PLOFILE_IMAGE',
  CREATE_KYC_DOCUMENTS: 'CREATE_KYC_DOCUMENTS',
  GET_KYC_DOCUMENTS: 'GET_KYC_DOCUMENTS',
  SEND_VERIFICATION_SMS: 'SEND_VERIFICATION_SMS',
  VERIFY_SMS: 'VERIFY_SMS',
  START_KYC: 'START_KYC',
  GET_KYC_STATUS: 'GET_KYC_STATUS',
  GET_ICO_USERS_INFO: 'GET_ICO_USERS_INFO',
  GET_COMPLIANCE_INFO: 'GET_COMPLIANCE_INFO',
  CHECK_PIN: 'CHECK_PIN',
  CHECK_TWO_FACTOR: 'CHECK_TWO_FACTOR',
  DISABLE_TWO_FACTOR: 'DISABLE_TWO_FACTOR',
  CONNECT_PHONE_CONTACTS: 'CONNECT_PHONE_CONTACTS',
  GET_CONNECT_CONTACTS: 'GET_CONNECT_CONTACTS',
  GET_LINKED_BANK_ACCOUNT: 'GET_LINKED_BANK_ACCOUNT',
  LINK_BANK_ACCOUNT: 'LINK_BANK_ACCOUNT',
  GET_LOYALTY_INFO: "GET_LOYALTY_INFO",
  GET_MEMBER_STATUS: "GET_MEMBER_STATUS",
  GET_APP_SETTINGS: "GET_APP_SETTINGS",
  SET_APP_SETTINGS: "SET_APP_SETTINGS",
  GET_USER_SECURITY_OVERVIEW: "GET_USER_SECURITY_OVERVIEW",

  // wallet api calls
  GET_WALLET_DETAILS: 'GET_WALLET_DETAILS',
  GET_WALLET_SUMMARY: 'GET_WALLET_SUMMARY',
  GET_COIN_BALANCE: 'GET_COIN_BALANCE',
  GET_COIN_ADDRESS: 'GET_COIN_ADDRESS',
  GET_COIN_ORIGINATING_ADDRESS: 'GET_COIN_ORIGINATING_ADDRESS',
  SET_COIN_WITHDRAWAL_ADDRESS: 'SET_COIN_WITHDRAWAL_ADDRESS',
  CHECK_USER_PIN_STATUS: 'CHECK_USER_PIN_STATUS',
  SET_PIN: 'SET_PIN',
  WITHDRAW_CRYPTO: 'WITHDRAW_CRYPTO',
  GET_TRANSACTION_DETAILS: 'GET_TRANSACTION_DETAILS',
  GET_ALL_TRANSACTIONS: 'GET_ALL_TRANSACTIONS',
  GET_COIN_TRANSACTIONS: 'GET_COIN_TRANSACTIONS',
  GET_ALL_COIN_WITHDRAWAL_ADDRESSES: "GET_ALL_COIN_WITHDRAWAL_ADDRESSES",

  // graph action
  GET_WALLET_BALANCE_DATA: 'GET_WALLET_BALANCE_DATA',
  GET_COIN_WALLET_BALANCE_DATA: 'GET_COIN_WALLET_BALANCE_DATA',
  GET_INTEREST_GRAPH_DATA: 'GET_INTEREST_GRAPH_DATA',
  GET_COIN_INTEREST_GRAPH_DATA: 'GET_COIN_INTEREST_GRAPH_DATA',

  // root api calls
  GET_SUPPORTED_CURRENCIES: 'GET_SUPPORTED_CURRENCIES',
  GET_BACKEND_STATUS: 'GET_BACKEND_STATUS',
  GET_KYC_DOC_TYPES: 'GET_KYC_DOC_TYPES',
  GET_INITIAL_CELSIUS_DATA: 'GET_INITIAL_CELSIUS_DATA',

  // interest api calls
  GET_INTEREST_RATES: 'GET_INTEREST_RATES',
  GET_INTEREST_CHART_DATA: 'GET_INTEREST_CHART_DATA',

  // currencies api calls
  GET_CURRENCY_RATES: 'GET_CURRENCY_RATES',
  GET_CURRENCY_GRAPHS: 'GET_CURRENCY_GRAPHS',

  // transfer api calls
  GET_ALL_TRANSFERS: 'GET_ALL_TRANSFERS',
  GET_TRANSFER: 'GET_TRANSFER',
  CLAIM_TRANSFER: 'CLAIM_TRANSFER',
  CANCEL_TRANSFER: 'CANCEL_TRANSFER',
  CREATE_TRANSFER: 'CREATE_TRANSFER',

  // branch calls
  CREATE_BRANCH_LINK: 'CREATE_BRANCH_LINK',
  SAVE_BRANCH_LINK: 'SAVE_BRANCH_LINK',
  GET_LINK_BY_URL: 'GET_LINK_BY_URL',
  CHECK_PROFILE_PROMO_CODE: "CHECK_PROFILE_PROMO_CODE",
  SUBMIT_PROMO_CODE: "SUBMIT_PROMO_CODE",
  GET_INDIVIDUAL_LINK: "GET_INDIVIDUAL_LINK",

  // camera roll calls
  GET_CAMERA_ROLL: 'GET_CAMERA_ROLL',
  TAKE_CAMERA_PHOTO: 'TAKE_CAMERA_PHOTO',

  // community statistics
  GET_COMMUNITY_STATISTICS: "GET_COMMUNITY_STATISTICS",

  // loan calls
  APPLY_FOR_LOAN: 'APPLY_FOR_LOAN',
  GET_ALL_LOANS: 'GET_ALL_LOANS',

  // apy key calls
  CREATE_API_KEY: 'CREATE_API_KEY',
  DELETE_API_KEY: 'DELETE_API_KEY',
  GET_API_KEYS: 'GET_API_KEYS'
}
