const FONTS = [
  {'barlow-regular': require('../../assets/fonts/Barlow/Barlow-Regular.otf')},
  {'barlow-bold': require('../../assets/fonts/Barlow/Barlow-Bold.otf')},
  {'barlow-bold-italic': require('../../assets/fonts/Barlow/Barlow-BoldItalic.otf')},
  {'barlow-italic': require('../../assets/fonts/Barlow/Barlow-Italic.otf')},
  {'barlow-semibold': require('../../assets/fonts/Barlow/Barlow-SemiBold.otf')},
];

const CACHE_IMAGES = [
  // require('../../../assets/images/illustrations-v3/PolarBearFistUp3x.png'),
  // require('../../../assets/images/illustrations-v3/PolarBearFistUp3x.png'),
  // require('../../../assets/images/illustrations-v3/PolarBearFistUp3x.png'),
  // require('../../assets/images/icons/celsius_symbol_white.png'),
  // require('../../assets/images/icons/animated-spinner.gif'),
  // require('../../assets/images/icons/white_spinner.gif'),
  // require('../../assets/images/icons/icon-check.png'),
  // require('../../assets/images/icons/camera-flip.png'),
  // require('../../assets/images/two-thumbs-up.png'),
  // require('../../assets/images/bubble-pointer.png'),
  // require('../../assets/images/avatar-mouse-girl.jpg'),
  // require('../../assets/images/avatar-bear.jpg'),
  // require('../../assets/images/avatar-cat.jpg'),
  // require('../../assets/images/avatar-deer.jpg'),
  // require('../../assets/images/avatar-girl-dog.jpg'),
  // require('../../assets/images/avatar-hippo.jpg'),
  // require('../../assets/images/avatar-monkey.jpg'),
  // require('../../assets/images/avatar-monkey-girl.jpg'),
  // require('../../assets/images/avatar-sheep.jpg'),
  // require('../../assets/images/camera-mask-circle.png'),
  // require('../../assets/images/camera-mask-document.png'),
  // require('../../assets/images/phone_doggirl3x.png'),
  // require('../../assets/images/bear-NoKYC3x.png'),
  // require('../../assets/images/bear-happyKYC3x.png'),
  // require('../../assets/images/frenchy.png'),
  // require('../../assets/images/interest-illu.png'),
  // require('../../assets/images/deerTransactionHistory.png'),
  // require('../../assets/images/illuNoKYC3x.png'),
  // require('../../assets/images/OfflineMode/deer-tangled3x.png'),
  // require('../../assets/images/Onboarding_background3x.png'),
  // require('../../assets/images/interactivePart3x.png'),
  // require('../../assets/images/Conversation3x.png'),
  // require('../../assets/images/security_dog3x.png'),
  // require('../../assets/images/Group_232-3x.png'),
  // require('../../assets/images/authSuccess3x.png'),
  // require('../../assets/images/hodl-bear.png'),
  // require('../../assets/images/7pie.png'),
  // require('../../assets/images/9pie.png'),
  // require('../../assets/images/12pie.png'),
  // require('../../assets/images/diane-with-laptop3x.png'),
  // require('../../assets/images/squirrel-modal3x.png'),
  // require('../../assets/images/celsius-logo3x.png'),
  require('../../assets/images/bear-happyKYC3x.png'),
  require('../../assets/images/deerTransactionHistory.png'),
  require('../../assets/images/illuNoKYC3x.png'),
  require('../../assets/images/OfflineMode/deer-tangled3x.png'),
  require('../../assets/images/diane-sad.png'),
];

export default {
  FONTS,
  CACHE_IMAGES,
}
