platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

target 'celsius' do
  # pod 'AppCenter/Crashes'
  # pod 'AppCenter/Analytics'
  # pod 'AppCenterReactNativeShared'
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for celsius
  # pod 'React', :path => '../node_modules/react-native', :subspecs => [
  #   'Core',
  #   'CxxBridge',
  #   'DevSupport',
  #   'RCTText',
  #   'RCTNetwork',
  #   'RCTWebSocket',
  #   'RCTAnimation',
  #   'RCTImage',
  #   'RCTCameraRoll'
  # ]

  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
  pod 'React-RCTCameraRoll', :path => '../node_modules/react-native/Libraries/CameraRoll'


  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  use_unimodules!



  # CodePush plugin dependency
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  # Appsflyer plugin dependency
  pod 'react-native-appsflyer', :path => '../node_modules/react-native-appsflyer'

  pod 'Mixpanel'

  pod 'react-native-idfa', :path => '../node_modules/react-native-idfa'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'


  pod 'react-native-branch', :path => '../node_modules/react-native-branch'



  pod 'appcenter', :path => '../node_modules/appcenter'

  pod 'appcenter-analytics', :path => '../node_modules/appcenter-analytics'

  pod 'appcenter-crashes', :path => '../node_modules/appcenter-crashes'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end

  target 'celsiusTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
  
      if target.name == "yoga"
        target.remove_from_project
      end
    end
  end
  
end
