platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

target 'celsius' do
  pod 'AppCenter/Crashes', '~> 2.1.0'
  pod 'AppCenter/Analytics', '~> 2.1.0'
  pod 'AppCenterReactNativeShared', '~> 2.1.0'
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for celsius
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTImage',
    'RCTCameraRoll'
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  use_unimodules!

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'


  # CodePush plugin dependency
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  # Appsflyer plugin dependency
  pod 'react-native-appsflyer', :path => '../node_modules/react-native-appsflyer'

  pod 'Mixpanel'

  pod 'react-native-idfa', :path => '../node_modules/react-native-idfa'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end

  target 'celsiusTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
  
      if target.name == "yoga"
        target.remove_from_project
      end
    end
  end
  
end
