export default {
  // loanRequest api calls
  CREATE_LOAN_REQUEST: 'CREATE_LOAN_REQUEST',
  GET_LOAN_REQUEST: 'GET_LOAN_REQUEST',
  CANCEL_LOAN_REQUEST: 'CANCEL_LOAN_REQUEST',
  GET_SUPPORTED_CURRENCIES: 'GET_SUPPORTED_CURRENCIES',
  ACCEPT_LOAN_REQUEST: 'ACCEPT_LOAN_REQUEST',
  STATUS_LOAN_REQUEST: 'STATUS_LOAN_REQUEST',
  GET_LOAN_DETAILS: 'GET_LOAN_DETAILS',
  CREATE_LOAN_DETAILS: 'CREATE_LOAN_DETAILS',

  // portfolio api calls
  GET_PORTFOLIO: 'GET_PORTFOLIO',
  CREATE_PORTFOLIO_REQUEST: 'CREATE_PORTFOLIO_REQUEST',
  GET_PORTFOLIO_REQUEST: 'GET_PORTFOLIO_REQUEST',

  
  // auth api calls
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_BORROWER: 'LOGIN_BORROWER',
  GET_LOGGED_IN_BORROWER: 'GET_LOGGED_IN_BORROWER',
  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_TWITTER: 'REGISTER_USER_TWITTER',
  LOGIN_USER_TWITTER: 'LOGIN_USER_TWITTER',
  REGISTER_USER_FACEBOOK: 'REGISTER_USER_FACEBOOK',
  LOGIN_USER_FACEBOOK: 'LOGIN_USER_FACEBOOK',
  REGISTER_USER_GOOGLE: 'REGISTER_USER_GOOGLE',
  LOGIN_USER_GOOGLE: 'LOGIN_USER_GOOGLE',
  UPDATE_USER: 'UPDATE_USER',
  REGISTER_BORROWER: 'REGISTER_BORROWER',
  REGISTER_EXISTING_BORROWER: 'REGISTER_EXISTING_BORROWER',
  SEND_RESET_LINK: 'SEND_RESET_LINK',

  CREATE_INTEREST_REQUEST: 'CREATE_INTEREST_REQUEST',
  EARN_INTEREST_QUERY: 'EARN_INTEREST_QUERY',

  // user api calls
  GET_USER_PERSONAL_INFO: 'GET_USER_PERSONAL_INFO',
  CREATE_USER_PERSONAL_INFO: 'CREATE_USER_PERSONAL_INFO',
  GET_USER_ADDRESS_INFO: 'GET_USER_ADDRESS_INFO',
  CREATE_USER_ADDRESS_INFO: 'CREATE_USER_ADDRESS_INFO',
  GET_USER_CONTACT_INFO: 'GET_USER_CONTACT_INFO',
  CREATE_USER_CONTACT_INFO: 'CREATE_USER_CONTACT_INFO',
  GET_USER_BANK_INFO: 'GET_USER_BANK_INFO',
  CREATE_USER_BANK_INFO: 'CREATE_USER_BANK_INFO',
  GET_USER_DOCUMENTS: 'GET_USER_DOCUMENTS',
  CREATE_USER_DOCUMENTS: 'CREATE_USER_BANK_INFO',


  COMPLETE_KYC: 'COMPLETE_KYC',
}
