export default {
  // portfolio api calls
  GET_PORTFOLIO: 'GET_PORTFOLIO',
  CREATE_PORTFOLIO_REQUEST: 'CREATE_PORTFOLIO_REQUEST',
  GET_PORTFOLIO_REQUEST: 'GET_PORTFOLIO_REQUEST',
  GET_ESTIMATED_LOAN: 'GET_ESTIMATED_LOAN',
  GET_ESTIMATED_INTEREST: 'GET_ESTIMATED_INTEREST',

  // auth api calls
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_BORROWER: 'LOGIN_BORROWER',
  GET_LOGGED_IN_BORROWER: 'GET_LOGGED_IN_BORROWER',
  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_TWITTER: 'REGISTER_USER_TWITTER',
  LOGIN_USER_TWITTER: 'LOGIN_USER_TWITTER',
  REGISTER_USER_FACEBOOK: 'REGISTER_USER_FACEBOOK',
  LOGIN_USER_FACEBOOK: 'LOGIN_USER_FACEBOOK',
  REGISTER_USER_GOOGLE: 'REGISTER_USER_GOOGLE',
  LOGIN_USER_GOOGLE: 'LOGIN_USER_GOOGLE',
  UPDATE_USER: 'UPDATE_USER',
  REGISTER_BORROWER: 'REGISTER_BORROWER',
  REGISTER_EXISTING_BORROWER: 'REGISTER_EXISTING_BORROWER',
  SEND_RESET_LINK: 'SEND_RESET_LINK',
  RESET_PASSWORD: 'RESET_PASSWORD',

  // user api calls
  GET_USER_PERSONAL_INFO: 'GET_USER_PERSONAL_INFO',
  UPDATE_USER_PERSONAL_INFO: 'UPDATE_USER_PERSONAL_INFO',
  UPLOAD_PLOFILE_IMAGE: 'UPLOAD_PLOFILE_IMAGE',
  CREATE_KYC_DOCUMENTS: 'CREATE_KYC_DOCUMENTS',
  SEND_VERIFICATION_SMS: 'SEND_VERIFICATION_SMS',
  VERIFY_SMS: 'VERIFY_SMS',

  // root api calls
  GET_SUPPORTED_CURRENCIES: 'GET_SUPPORTED_CURRENCIES',
}
